name: MMOShop
version: '${project.version}'
main: net.danh.mmoshop.MMOShop
api-version: 1.16
depend: [ MMOItems, MythicLib, PlaceholderAPI ]
authors: [ VoChiDanh ]
description: Plugins shop for MMOItems
commands:
  mmoshop:
    description: Main command
permissions:
  mmoshop.admin:
    default: op
  mmoshop.shop.*:
    default: false
  mmoshop.shop.<shopname>:
    default: false
